# Generated by Django 4.2.1 on 2025-07-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculator',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
