# Generated by Django 4.2.1 on 2025-07-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_calculator_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculator',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddIndex(
            model_name='calculator',
            index=models.Index(fields=['-time_create'], name='calc_calcul_time_cr_f53923_idx'),
        ),
    ]
