# Generated by Django 4.2.1 on 2025-07-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_alter_calculator_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'В разработке'), (1, 'Опубликовано')], default=0),
        ),
    ]
